core/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("l", views.index, name="index"),
    path("", views.record, name="record"),
    path("new/", views.new_voice, name="new"),
    path("record/detail/<uuid:id>/", views.record_detail, name="record_detail"),
    path("record/text/<str:id>/", views.text, name="text"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

record/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/_header.html
{% load static %}
<!--url cache-->
{% url 'core:record' as record_url %}
<!--url cache-->
{% url 'core:index' as home_url %}
<section class="hero is-info is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            
            <a class="navbar-item {% if request.path == record_url %} is-active {% endif %}" href="{% url 'core:record' %}"> Record </a>
          </div>
        </div>
      </div>
    </nav>
  </div>
</section>